export declare const CURSOR_SDK_EVENT_DEBUG_INTERNAL_RUN_DIR_ENV: "PI_CURSOR_SDK_EVENT_DEBUG_RUN_DIR";
export declare const CURSOR_SDK_EVENT_DEBUG_INTERNAL_SESSION_DIR_ENV: "PI_CURSOR_SDK_EVENT_DEBUG_SESSION_DIR";
export declare const CURSOR_SDK_EVENT_DEBUG_RUN_DIR_ENV: "PI_CURSOR_SDK_EVENT_DEBUG_RUN_DIR";
export declare const CURSOR_SDK_EVENT_DEBUG_SESSION_DIR_ENV: "PI_CURSOR_SDK_EVENT_DEBUG_SESSION_DIR";
export declare const CURSOR_SDK_EVENT_DEBUG_STALE_PUBLIC_ENV_NAMES: readonly [
	"PI_CURSOR_SDK_EVENT_DEBUG",
	"PI_CURSOR_SDK_EVENT_DEBUG_DIR",
	"PI_CURSOR_SDK_EVENT_DEBUG_STDERR",
];
export declare const CURSOR_SDK_EVENT_DEBUG_INTERNAL_ENV_NAMES: readonly [
	typeof CURSOR_SDK_EVENT_DEBUG_INTERNAL_RUN_DIR_ENV,
	typeof CURSOR_SDK_EVENT_DEBUG_INTERNAL_SESSION_DIR_ENV,
];
export declare const CURSOR_SDK_EVENT_DEBUG_ENV_NAMES: readonly [
	...typeof CURSOR_SDK_EVENT_DEBUG_STALE_PUBLIC_ENV_NAMES,
	...typeof CURSOR_SDK_EVENT_DEBUG_INTERNAL_ENV_NAMES,
];
